version: '3'

services:
  bot:
    image: ghcr.io/joshbuker/discord-bot:main
    depends_on:
      - ollama
      - automatic1111
    restart: unless-stopped
    tty: true
    environment:
      - RUBY_DISCORD_BOT_TOKEN=${RUBY_DISCORD_BOT_TOKEN:?Please configure RUBY_DISCORD_BOT_TOKEN}
      - DEFAULT_LLM_MODEL=${DEFAULT_LLM_MODEL:-"llama3"}
      # - OLLAMA_SERVICE_NAME=${OLLAMA_SERVICE_NAME:?Please configure OLLAMA_SERVICE_NAME}

  automatic1111:
    image: ghcr.io/joshbuker/automatic1111-docker:main
    volumes:
      - ~/Stable\ Diffusion/model:/model:ro
      - venv:/app/venv
      - repos:/app/repositories
    tty: true
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: [gpu]
              device_ids:
                - nvidia.com/gpu=all

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: [gpu]
              device_ids:
                - nvidia.com/gpu=all

volumes:
  ollama: {}
